### ISSUE TITLE
Changes for 1.9.3

### ISSUE THREAD

**Issue by ssborbis** [ssborbis/ContextSearch-web-ext#121]
Options facelift
Highlighting
Links & images can be searched using the Quick menu
Merged QM and Toolbar themes
Added expanding sitesearch icons when using templates with {selectdomain} param

...

@DenB10 I will probably release sometime next week. Most messages.json data is in the repo. I commented out the locale/css after doing some layout changes in options. It shouldn't be needed. Still need to rewrite the help page, but I'm considering making it web-based / wiki so people can use a translator. I'll let you know

**Comment by ssborbis** [comment]
> The new look of the options window is much better.

Thanks. It was long overdue.

> Highlighting is a good idea but it's a pity this feature only works with single word search.

What do you mean exactly? There's an option to search for each term separately. The API i'm using (mark.js) has a ton of options which I can add to the config.

> A web-based help page is a good idea but this page could be also translated...

Still trying to decide what would be best.

**Comment by DenB10** [comment]
> What do you mean exactly? There's an option to search for each term separately. The API i'm using (mark.js) has a ton of options which I can add to the config.

Excuse me, I've not read correctly, the highlighting feature works fine indeed. Maybe consider adding an option to color differently the separate search terms?

**Comment by hg42** [comment]
the new options page works very well, and access is much faster

* +1 for different colors for each word
* I think, the sidebar shouldn't share the number of columns and single columns layout with toolbar.
Instead all three menus should have their own settings.
And I don't quite understand why they have different features. Why not put tools and settings etc. in all menus?
Generally the three menus can be the same, with different configurable columns and possibly single column text menu.
I would probably configure toolbar as single column (because of the texts!), but currently the sidebar would display the same way, which I don't want
* sidebar is better with less columns, because it should stay out of the way (especially if kept open), while I use more columns for the toolbar, so I would need separate column settings
* however, for a narrow sidebar (say 3 columns), the search field and the suggestions are very short. perhaps these two areas could grow when hovering...or something like that, not sure what's the best way to solve this.
* the suggestions also use a much bigger font, which makes it worse (I know I can change that myself via css). I guess, that's because edit fields have a different formatting. Perhaps you can use the same style class for the suggestions?
* in the settings pages, I would recommend to put common settings at the top (so they are at the same place when switching), e.g. columns and single column layout etc., because you can easier compare.
* 3 column toolbar menu leaves empty space at the right side

**Comment by ssborbis** [comment]
> Maybe consider adding an option to color differently the separate search terms?

done

> I think, the sidebar shouldn't share the number of columns and single columns layout with toolbar.
Instead all three menus should have their own settings.

done

> however, for a narrow sidebar (say 3 columns), the search field and the suggestions are very short. perhaps these two areas could grow when hovering...or something like that, not sure what's the best way to solve this.

I'm guessing that would be a major pain due to iframes & resize messaging. Gonna hold off on that one

> the suggestions also use a much bigger font, which makes it worse

Must be some browser / platform discrepancies. They are within one pt for me (input = 10pt, suggestions = 11pt). Post a screenshot

> in the settings pages, I would recommend to put common settings at the top (so they are at the same place when switching), e.g. columns and single column layout etc., because you can easier compare.

Columns section looks the same now

> 3 column toolbar menu leaves empty space at the right side

FF has a minimum browser_action window size. I had some code to widen icons to fill the space but it was causing runaway window resizing under some circumstances so I left it out. I'll try to get a fix but in the meantime, you can use custom styles on a per-menu basis `#quickMenuElement[data-menu="searchbar"] .tile:not(.singleColumn) { width: 48px;}`

**Comment by ssborbis** [comment]
Highlighting glitch in Chrome. 

Working on it...

**Comment by narcolepticinsomniac** [comment]
Suppose a case for either could be made. All together is convenient, separate is more configurable. If you like dark, you probably want them all dark and vice versa, IMO.

On a related note, you should probably lose the border transition on `.tile`. It's not being used, and it's applied in a glitchy looking way when the widget loads. More noticeable with the dark theme in the quick menu,

**Comment by ssborbis** [comment]
> On a related note, you should probably lose the border transition on .tile. It's not being used, and it's applied in a glitchy looking way when the widget loads. More noticeable with the dark theme in the quick menu,

All the animations look glitchy on Chrome for me. From what I've seen t doesn't handle transitions well. If it's just the border causing issues that would be great.

**Comment by narcolepticinsomniac** [comment]
It is in this case for me. FF and Chrome are both buggy and inconsistent about applying transitions on page load IMO. Worse with less common ones like borders. We implemented [a workaround](https://github.com/openstyles/stylus/blob/master/content/apply.js#L448) to prevent them in another project I'm involved with, not that you need anything that drastic.

**Comment by ssborbis** [comment]
Cool I'll play around with that fix but I don't think I'm seeing the same issue you are. I'll probably need to have you test. I'll let you know when I have something. Won't be today.

**Comment by ssborbis** [comment]
Are you able to fix the problem with a CSS style on .tile elements? Overriding the transition effect skipping the border-color?

**Comment by narcolepticinsomniac** [comment]
Deleting `border-color .25s ease-out` from `.tile` in `quickmenu.css` fixed the glitchiness for me. You're not changing border color on hover anyway, so NBD.

**Comment by ssborbis** [comment]
Cool I'll axe it

**Comment by ssborbis** [comment]
@narcolepticinsomniac 
CSS is updated

@hg42 
I put the Toolbar fix for low columns back. Let me know if you see any runaway resizing.

**Comment by narcolepticinsomniac** [comment]
Came across a couple errors. No real context for ya, unfortunately, but maybe they'll tell you something:

![error 1](https://user-images.githubusercontent.com/14100003/49877695-fa1ec180-fdf3-11e8-9ecc-9efd0200b614.png)

![error 2](https://user-images.githubusercontent.com/14100003/49877723-0dca2800-fdf4-11e8-89e5-0b09636064a0.png)

**Comment by ssborbis** [comment]
@narcolepticinsomniac 
> Came across a couple errors

Hmm...I can't reproduce but my concern is the code for updating the userOptions with new keys isn't working properly

Are you using the latest repos?

Does it happen on every page or just google?

Go into CS options and open the console. What's the object look like for `userOptions.sideBar` and `userOptions.highLight`?

**Comment by narcolepticinsomniac** [comment]
I only pointed them out in case they highlighted any obvious issues. IDK when they showed up, or from which version. I've reloaded a few recent updates, but it wasn't the most recent. I just updated to the most recent and I can't repro either. Very likely irrelevant.

I see some errors on the options page for what appear to be non-existent OS logo images, and an incorrect path `_locales/en-US/style.css`, which should be`/en/` AFAICT.

![option page errors](https://user-images.githubusercontent.com/14100003/49887999-dd8e8380-fe0b-11e8-8a4d-548afbe4f208.png)

**Comment by ssborbis** [comment]
> I only pointed them out in case they highlighted any obvious issues. IDK when they showed up, or from which version. I've reloaded a few recent updates, but it wasn't the most recent. I just updated to the most recent and I can't repro either. Very likely irrelevant.

Ok good. Hopefully that problem is fixed now.

> I see some errors on the options page for what appear to be non-existent OS logo images, and an incorrect path _locales/en-US/style.css, which should be/en/ AFAICT.

Ugh, help page. I'm really dragging my feet on that one.

If I'm remembering the i18n API correctly,  because your `_locale` is set to `en-US`, it looks in that folder first for locale-specific styling and falls back to `en`. That way I don't need a en-GB, en-US, en-*whatever* folders. No biggie

**Comment by hg42** [comment]
wow, lot's of improvements to discover...

> > Maybe consider adding an option to color differently the separate search terms?
> done

thanks...top!

> > I think, the sidebar shouldn't share the number of columns and single columns layout with toolbar.
> > Instead all three menus should have their own settings.
> done

wow....now I can try even more variants...I am still not sure which is the most efficient configuration.
(with every new feature comes a new small wish...the toolbar single column menu is only half of my screen and I need to scroll. I think mozilla sets such limits, right?

In settings, "Opening - Overlay an icon for opening the sidebar" should probbaly at least mention, that the prescious button is a drop target. For me it's a main feature (naturally, because I suggested it, haha). I think this kind of usage is not very well known, but it is very convenient, if a user likes drag and drop, so I think it should be promoted.
I notice that drag and drop features are often reduced nowadays, which makes me sad...instead text interfaces get a hype now...looks like the world is turning top down...

> > however, for a narrow sidebar (say 3 columns), the search field and the suggestions are very short
> I'm guessing that would be a major pain due to iframes & resize messaging. Gonna hold off on that one

jepp, I even don't know how it could be designed to work fluently

> > And I don't quite understand why they have different features. Why not put tools and settings etc. in all menus?
> Tools are only useful to the Quick menu right now

I am not sure why you think this. I admit I don't use copy etc. very much, but I often want to open settings from the quickmenu or from the sidebar. Then I need to close it and goto the toolbar. Generally, I do not distinguish very much between these three menus. All three are  vying for my favor and I can't decide. It's a matter of accessability and of features.
E.g. the quickmenu doesn't have suggestions and currently the sidebar is to narrow to show these. So the toolbar is used. The toolbar is also the only one available on internal firefox pages. The sidebar collects it's points via the drag and drop feature and is certainly used most often. From the day the sidebar existed, the quickmenu dropped from top to bottom of the list.

> > the suggestions also use a much bigger font, which makes it worse
> Must be some browser / platform discrepancies. They are within one pt for me (input = 10pt, suggestions = 11pt). Post a screenshot

interesting...the behavior changed with the last pull and I now have the same *big* font in both :-)
I have forced all fonts to small size now, which works well (though it takes some time until the new css is really used, I currently don't see why, but I have about a 100 tabs now, however, most should be suspended).

> > in the settings pages, I would recommend to put common settings at the top (so they are at the same place when switching), e.g. columns and single column layout etc., because you can easier compare.
> Columns section looks the same now

well done, thanks, this already helped...

> > 3 column toolbar menu leaves empty space at the right side
> FF has a minimum browser_action window size. I had some code to widen icons to fill the space but it was causing runaway window resizing under some circumstances so I left it out. I'll try to get a fix but in the meantime, you can use custom styles on a per-menu basis `#quickMenuElement[data-menu="searchbar"] .tile:not(.singleColumn) { width: 72px;}`

well, I didn't like the wider buttons very much, either :-)
I certainly would never have tried less than 5 columns in the toolbar menu, but it happened to share it's setting with the sidebar.
So this is already solved now, because you gave us a column setting for each menu type.

Thanks again for all the work...

**Comment by hg42** [comment]
> Anyone see themselves using a separate theme setting per menu?

nope...

though I would probably like to handle the menu types differently in custom CSS. I assume you didn't break that?
I didn't try, but I think I can use ```body[data-menu="sidebar"]``` etc. for that, right? That should also be enough for users with special interests.

**Comment by ssborbis** [comment]
>  toolbar single column menu is only half of my screen and I need to scroll. I think mozilla sets such limits, right?

Yep, min/max width/height. Auto-resizes too It's a pain to work around

> In settings, "Opening - Overlay an icon for opening the sidebar" should probbaly at least mention, that the prescious button is a drop target.

Sure why not.

> interesting...the behavior changed with the last pull and I now have the same big font in both :-)

I set them both to 11pt. We must be using different resolutions or something because I wouldn't call either fonts "big"

> I am not sure why you think this. I admit I don't use copy etc. very much, but I often want to open settings from the quickmenu or from the sidebar. Then I need to close it and goto the toolbar. Generally, I do not distinguish very much between these three menus. All three are vying for my favor and I can't decide. It's a matter of accessability and of features.

My bad. I thought you were talking about the Open As Link, Copy, Close, Power, Lock tools. Yeah, I've been annoyed at having to open the toolbar to get to options too. I'll throw the button back in the sidebar and maybe add a 'tool' button for the qm. I suppose I could add the option for suggestions in the qm if it's not too much of a hassle. Right now all the suggestions code is in the toolbar/sidebar scripts.

> though I would probably like to handle the menu types differently in custom CSS. I assume you didn't break that?
I didn't try, but I think I can use body[data-menu="sidebar"] etc. for that, right? That should also be enough for users with special interests.

Should work. If not, `#quickMenuElement[data-menu="sidebar"]` but pretty sure I added the data to the body also for this purpose. Lots of moving parts. hard to remember all the changes

**Comment by hg42** [comment]
yes, user styles are ok. This way I get everything small...I simply use `* { font-size: 9px; }`. This also gives me a much smaller single column menu.

I copied this screenshot to give you some hint how it works for me...it's two 2048x1152 screens (the other is for real projects).
I am certainly a special user. I know none like this in my local area. However, on the internet, there are many. You can easily find them at browser issue trackers begging for vertical tabs and similar tools.

**Comment by ssborbis** [comment]
1.9.3 released

**Comment by ssborbis** [comment]
Thanks everyone for the input and contributions

**Comment by narcolepticinsomniac** [comment]
Thanks for all your contributions, since you're doing the heavy lifting here. =) This extension is one of my new favorite toys. Still hoping root domain and end of path w/out forward slashes make it into domain search options, as discussed [here](https://github.com/ssborbis/ContextSearch-web-ext/issues/117#issuecomment-445063043). You seemed to agree at the time, but you were working on a bunch of different features at once, so I'm not sure if that detail got lost in the mix.

**Comment by ssborbis** [comment]
Repo updated

![untitled](https://user-images.githubusercontent.com/24310997/50047711-9b21ac80-0080-11e9-9792-840e7b718efb.png)

**Comment by ssborbis** [comment]
@narcolepticinsomniac 

Patch going up. Didn't test much but the basics are there

**Comment by narcolepticinsomniac** [comment]
Not seeing any difference. Maybe a Chrome issue again?

**Comment by ssborbis** [comment]
Looks ok to me testing locally. Maybe the repo is slow or the push didn't go through?

In Chrome
![sitesearch](https://user-images.githubusercontent.com/24310997/50048537-894a0480-0094-11e9-84e7-d66628f6461e.gif)

**Comment by narcolepticinsomniac** [comment]
>I'm assuming the master is the same.

I don't think so. I'm testing loading it fresh in Canary now too, no dice. Not like I've never screwed up something simple task half a dozen times in a row, but I don't believe that's the case this time.

**Comment by ssborbis** [comment]
are you not seeing the highlighting because you have the searchbar hidden? What happens when you press enter?

**Comment by ssborbis** [comment]
Looks like hiding the searchbar causes problems. Working on it.

**Comment by narcolepticinsomniac** [comment]
Yep, that's the issue.

**Comment by ssborbis** [comment]
pushed. I'm still testing too

**Comment by narcolepticinsomniac** [comment]
Yep, LGTM now, thanks. I'll let you know if I run into any issues with it.
