### ISSUE TITLE
toolbar: do not store queries 

### ISSUE THREAD

**Issue by BlueMax** [ssborbis/ContextSearch-web-ext#170]
The toolbar always saves queries. Even if it doesn't show the last entries you can simply enter some chars and suggestions from previous queries kick in.
That could be a privacy issue. Can you add an option to not store queries at all (or for one session only)?
**_Remember search terms and display them with search suggestions_** is already turned off.

**Comment by ssborbis** [comment]
Hmm... if that's the case it's unintentional. I'll check the code and see what's going on.

... looks like there's a bug in the Clear Search History function. There may be some older queries that are being shown in the list. 

Try opening a browser console from ContextSearch options and entering this line

`userOptions.searchBarHistory = []; saveOptions();`

Let me know if that fixes things. I'll double-check the other methods also.

**Comment by ssborbis** [comment]
The code to display the history or not was checking whether the history array was empty instead of reading the `Remember search terms and display them with search suggestions` option.

Clearing the history *should* temporarily fix your issue, and the bugs are patched for the next release.

**Comment by BlueMax** [comment]
> Clearing the history _should_ temporarily fix your issue, and the bugs are patched for the next release.

Indeed, thank you!

**Comment by ssborbis** [comment]
Everything should be working in the latest release (1.9.8). I'll close the issue, but if you run into problems, I'll reopen and troubleshoot with you.

**Comment by BlueMax** [comment]
Actually, nothing changed with 1.9.8. I still see my previous entries in the toolbar as suggestions when i start typing. And 'clear history' doesn't wipe them anymore.

**Comment by ssborbis** [comment]
@BlueMax 

What are your settings in the Toolbar section of CS options? I can't see any reason the Clear History function wouldn't be working. Do you see the green checkmark when you click `Clear History`? What does the array look like when you type `userOptions.searchBarHistory` in the console from the options page?

**Comment by BlueMax** [comment]
> What are your settings in the Toolbar section of CS options?

All off but 'Close the Toolbar Search menu after performing a search'.

>Do you see the green checkmark when you click `Clear History`?

Yes.

>What does the array look like when you type `userOptions.searchBarHistory` in the console from the options page? Any error messages in the console?

Says "length: 0" and there are no errors in the console.

**Comment by ssborbis** [comment]
Ah, that's FF, not this addon. There's a setting somewhere for keeping form data

**Comment by ssborbis** [comment]
https://support.mozilla.org/en-US/kb/control-whether-firefox-automatically-fills-forms#w_prevent-firefox-from-storing-form-entries

**Comment by BlueMax** [comment]
Indeed. That will wipe the history.
Thanks!
