### ISSUE TITLE
Import of previous export in 1.11 does not work

### ISSUE THREAD

**Issue by Carottinger** [ssborbis/ContextSearch-web-ext#192]
When re-importing a previous 1.11 export (file contains 21 search engines) the list of search engines is empty, cannot be restored or a new one added. Even after re-install this remains even though the list is reset.

**Comment by ssborbis** [comment]
Can you send me your .json file? I tried with an older config and it imported ok.

**Comment by ssborbis** [comment]
Oh, and I have seen a bug that requires the browser to be restarted before the search engine list will show but I thought it was fixed. Either way, send your config and I'll try importing and checking for errors.

**Comment by Carottinger** [comment]
[ContextSearchOptions.zip](https://github.com/ssborbis/ContextSearch-web-ext/files/3451311/ContextSearchOptions.zip)
The error still exists - and even though I have still several engines defined, the v13 export is completely empty!
Also the wikipedia search does not work anymore even though I verified the URL https://de.wikipedia.org/w/index.php?search={searchTerms}. Instead, Wikipedia is called without any searchTerms
Looks like v13 is pretty broken ...

**Comment by ssborbis** [comment]
I imported your v1.11 file to a new profile and got this.

![Untitled](https://user-images.githubusercontent.com/24310997/62231691-29397180-b38a-11e9-9668-7361384ef462.png)

All the engines appear usable, but they've been hidden. I'll have to look through the code to see why that happened. I saw you had one-click versions of the same engines as well. There must be a glitch in how those types of duplicates are imported when the profile doesn't have a one-click version.

> The error still exists - and even though I have still several engines defined, the v13 export is completely empty!

I can export that newly-imported config ok. 

What platform are you on?

**Comment by ssborbis** [comment]
Try this

[1.13.json.zip](https://github.com/ssborbis/ContextSearch-web-ext/files/3453054/1.13.json.zip)

**Comment by Carottinger** [comment]
> What version / platform are you on?
Linux/ubuntu 18.04/elementaryos 5.0 with FF 68.0.1

**Comment by Carottinger** [comment]
What can I do to load this json so that it works liek with ou? If I import the 1.13.json it does not create the engine list. Shall I remove and re-install the extension? Creating a new FF  profile is quite cumbesome just to reload the list.

**Comment by Carottinger** [comment]
![cswe](https://user-images.githubusercontent.com/48221698/62278396-49c80100-b448-11e9-866b-6afa7f9b4968.jpg)
This it how it looks when I remove the extension, restart FF and re-install it - empty list.
![cswe-init](https://user-images.githubusercontent.com/48221698/62279168-d9ba7a80-b449-11e9-8252-22831aa6dbb1.png)

After reloading you json version my engines are usable be still do not appear.
Do I have to cleanup something to get a clean extension?

**Comment by ssborbis** [comment]
> Do I have to cleanup something to get a clean extension?

You can try uninstalling / reinstalling the add-on and then importing the config I uploaded. If that doesn't work, I'll have to check your debug logs to see what's up.

I'll also check my ubuntu install to see if anything weird is happening with 'nix.

**Comment by ssborbis** [comment]
Did all of your settings go blank in options? I just checked on ubuntu and there's definitely a bug in the options page. Check your console ( ctrl+shift+K ) and look for something like this

```Error: Error: An unexpected error occured ........................ options.js 352:11```

**Comment by ssborbis** [comment]
Ok, it looks like there's a bug in Firefox. The API to get the one-click engines is failing ( browser.search.get() ) causing some cascade failures.

**Comment by ssborbis** [comment]
Check your Help -> About Firefox dialog and see if you're using the "Canonical" build. If so, that's the issue. Using the official Firefox release should fix the problem.

**Comment by ssborbis** [comment]
After filing a bug with bugzilla, the error appears to be caused by one-click search engines in Firefox Options -> Search that are missing an icon. Simply delete those engines ( Amazon for me ) and the problem should be fixed.

https://bugzilla.mozilla.org/show_bug.cgi?id=1570700

**Comment by Carottinger** [comment]
Perfect, that solves the problem of the lost list, the empty export and the non-functional wikipedia search. Thx a lot!
