### ISSUE TITLE
suggestion for drag and drop search feature

### ISSUE THREAD

**Issue by Amin884** [ssborbis/ContextSearch-web-ext#279]
Is it possible to have a drag and drop search feature like Captain Caveman's Web Search Pro?I am currently using Simple Drag & Drop Search alongside ContextSearch for some of my most used search engines but it is very limited.for me it is the only feature that is missing from ContextSearch to make it perfect.

**Comment by ssborbis** [comment]
I'm not familiar with that extension. What is the drag & drop feature you're wanting?

**Comment by Amin884** [comment]
I suggest you use "Simple Drag & Drop Search" add-on.you can select a text and when you drag that text your search engines will shown as tiles and you drop your text in engine you want.

**Comment by ssborbis** [comment]
Interesting feature. Would you want the same 8 tile setup ( first 8 engines in menu )?

**Comment by Amin884** [comment]
actually one of the limits "Simple Drag & Drop Search" has is the number of engines."Web Search Pro" had 3 options up to 64 tiles which I personally think is too much.and you could assign tiles to search engines.maybe you can do that with a drop down list with tile number in engine setting?
 ![web_search_pro_08](https://user-images.githubusercontent.com/70687284/92207326-49493780-ee9e-11ea-9981-75acea4bceb7.gif)
![web_search_pro_10](https://user-images.githubusercontent.com/70687284/92207344-4fd7af00-ee9e-11ea-90f3-7ce87aad2030.gif)

**Comment by ssborbis** [comment]
It's not too complicated to add something similar, but I'm wondering if I could simply add the option to open the quick menu on text-drag and you could use some CSS to enlarge the menu to achieve more or less the same effect. The menu already handles text drop ( in FF at least )

What's the benefit of having the larger tiles vs using the icons in the quick menu? Speed?

**Comment by Amin884** [comment]
Yes it is faster and easier to use because tiles position are fixed but quick menu position is based on text position.
but I guess if you could open quick menu on text drag and maximize it with transparent background it's almost the same thing.maybe just the pattern and lack of empty tiles are differences?

**Comment by ssborbis** [comment]
It's not pretty and options are limited, but I have it working. I'll spend some time refining it a little for testing before uploading anything to the repo.

**Comment by Amin884** [comment]
Thank you for working on it.I appreciate it

**Comment by ssborbis** [comment]
My original idea was to make a special folder in the search engines manager to drag & drop engines to, but it's a pain to copy each engine and place the copy in the folder. I'll probably have to build a grid-like widget similar to what the original add-on used. I might not have anything great before the next release, but I'll get something.

**Comment by Amin884** [comment]
thanks again.when do you think the next release come out?

**Comment by ssborbis** [comment]
The UI is coming along. I'm sure there are plenty of bugs, but hopefully I'll get a release out in a few days for testing.

![Untitled](https://user-images.githubusercontent.com/24310997/95823038-910b7c00-0cf2-11eb-87e7-b782451970c1.png)

**Comment by dnknn** [comment]
Can you use a simple gif to demonstrate the functionality of `Page Tiles` ?

`enablePageTiles` of `/options.html#advanced` ,  I never knew what it meant

**Comment by ssborbis** [comment]
> Can you use a simple gif to demonstrate the functionality of `Page Tiles` ?
> 
> `enablePageTiles` of `/options.html#advanced` , I never knew what it meant

In the latest repo version, there's a new tab in CS options named Page Tiles. The old way ( using the option in advanced ) is obsolete.

**Comment by ssborbis** [comment]
@dnknn I just realized there was still some old code that was requiring a "Page Tiles" folder to exist causing Page Tiles to not work for other users. That's fixed now in the repo.

**Comment by dnknn** [comment]
@ssborbis I want to trouble you to record a simple gif demo, because I still don't understand, Because the browser I use has a drag and drop function.

<details>
<summary>Details</summary>

![2010_15174438](https://user-images.githubusercontent.com/10995302/96106739-220a6f00-0f0e-11eb-9dcc-fd52415b11c9.png)

</details>

**Comment by ssborbis** [comment]
using a test profile with default settings...

![demo](https://user-images.githubusercontent.com/24310997/96198339-2a68a700-0f1a-11eb-9d73-37d7b276e2db.gif)

**Comment by dnknn** [comment]
> using a test profile with default settings...

Thank you very much, I fully understand now. and I tested it with the latest repo experience, I personally think that this function is not necessary and has little practical significance. 
In addition, there are many browsers (especially fork of Chromium) 
Google's official Chrome/Chromium may also natively support the super drag-drop function in the future.
So, I personally think that this feature is not necessary, for me personally, I will not enable it.


![2010_15174438](https://user-images.githubusercontent.com/10995302/96106739-220a6f00-0f0e-11eb-9dcc-fd52415b11c9.png)


![123456](https://user-images.githubusercontent.com/10995302/96244210-58142580-0fd8-11eb-8b47-997b18185d35.gif)

**Comment by ssborbis** [comment]
@Amin884 
v1.27 live on AMO. ChromeStore in a day or 2

**Comment by Amin884** [comment]
thank you.I've been using it for hours now.I really liked the freedom with the number of tiles.there are some issues but nothing important.
you can even add some default tiles like "save image/link..." , "copy text/link..."  or things like that.

**Comment by ssborbis** [comment]
> there are some issues but nothing important.

I'm sure there will be bugs, but at least it's out there to test now.

> you can even add some default tiles like "save image/link..." , "copy text/link..." or things like that.

That sounds like what some chromium forks have built-in. @dnknn mentioned them earlier in the thread . I guess FIrefox is late to that particular party, or they're leaving it to some other mouse gesture add-ons.

**Comment by dnknn** [comment]
Yes, Generally, some third-party chromium forks browsers will have drag-drop function, so this and `CS` drag-drop function cannot be enabled at the same time.

**Comment by Amin884** [comment]
>  That sounds like what some chromium forks have built-in. @dnknn mentioned them earlier in the thread . I guess FIrefox is late to that particular party, or they're leaving it to some other mouse gesture add-ons.

I know but they are usually direction-base not tile-base

**Comment by ssborbis** [comment]
@Amin884 

I'm open to suggestions if you want to make a list here to append / edit

**Comment by Amin884** [comment]
> 
> 
> @Amin884
> 
> I'm open to suggestions if you want to make a list here to append / edit

I think blank tiles should be transparent.also when you drag and drop to a blank tile it should close the window but currently it remains open.they should work as some kind of a cancel button.

there is a issue with direction of tiles.it is inherited from the page.in rtl sites the first tile goes to right side of the screen.

another problem for me was favicons.most of them are 16*16 and they don't look good in this design.

**Comment by ssborbis** [comment]
> there is a issue with direction of tiles. it is inherited from the page. in rtl sites the first tile goes to right side of the screen.

Do you have an site url I can test on?

> I think blank tiles should be transparent

Fully transparent seems weird to me but I'll try it and add a css rule so you can modify empty tiles with custom css.

> .also when you drag and drop to a blank tile it should close the window but currently it remains open.they should work as some kind of a cancel button.

Seems reasonable

> another problem for me was favicons.most of them are 16*16 and they don't look good in this design.

Oh, they look terrible, but they're easy to recognize blown up. There's a balance there somewhere, I just haven't found it yet.

**Comment by Amin884** [comment]
> Do you have an site url I can test on?

sure.check this for example:
https://www.tarafdari.com/

**Comment by ssborbis** [comment]
> sure.check this for example:
https://www.tarafdari.com/

K, fix is ready.

**Comment by Amin884** [comment]
thank you

**Comment by ssborbis** [comment]
Any suggestions or changes you'd like to see on this feature? I can probably get them in before the next release.

**Comment by Amin884** [comment]
> 
> 
> Any suggestions or changes you'd like to see on this feature? I can probably get them in before the next release.

No I don't have any new suggestion except the things we discussed before.but there is a new problem.sometimes when you select a text and drag it, nothing is selected in the pop-up screen.you have to select the text again.

Everything else is perfect.thank you.

**Comment by ssborbis** [comment]
https://github.com/ssborbis/ContextSearch-web-ext/issues/304#issuecomment-763455841

**Comment by ssborbis** [comment]
Tons of new features in v1.28

**Comment by ssborbis** [comment]
Heads up to anyone using this, as of the latest push, the menu was moved from the host page's document to an IFRAME for security and other reasons. User styles CSS selectors have changed and there will be a slight increase in loading time.

**Comment by ssborbis** [comment]
@Amin884 
> there is a new problem.sometimes when you select a text and drag it, nothing is selected in the pop-up screen.you have to select the text again.

I think I have this figured out. I'm guessing you're using a HOLD method for opening the quick menu?

**Comment by hg42** [comment]
nice feature...very useful

I recall something from the beginning...
I used to drag text to the firefox search bar at that time, but I also tried this tiling thing.
Then you implemented dragging to the sidebar (or if closed, to the little icon), because firefox restricted access to it's own areas.
Basically, when dragging, the context menu could be opened. The rest is more a matter of size.
But it is especially nice to have all folders open. On my 43" screen there is plenty of space for this :-)

suggestions:
* when clicking on something outside of the tiles, they should close
* when canceling the drag (escape), the tiles should also close, because they do nothing in this case
* maybe the tiles should open after some configurable timeout, in case there are other targets for dragging. It didn't happen, yet, but I am waiting for such a situation...
* I think the tiles should not be rounded, it's a bit irritating, if something lurks through the holes, especially when animated
* I would generally prefer the look of the context menu (but big) and it would be more consistent to use the same design. I guess, something (e.g. colors) that works with the context menu should also work with the tiles.
* I have several engines with longer titles, I would suggest attaching the icon to the bottom and a smaller font size (though I already changed it in CSS).

**Comment by ssborbis** [comment]
> when clicking on something outside of the tiles, they should close

Did you mean elsewhere on the desktop? I'm trying some event listeners and nothing seems to register a click outside the browser or elsewhere in the browser UI as an event ( no window blur, etc )

> when canceling the drag (escape), the tiles should also close, because they do nothing in this case

drag events seem to capture keypress events, and the first ESC will cancel the drag ( in FF at least ). It doesn't register with keypress listeners so I can't see it. It doesn't even throw a dragend event. You need to press ESC twice. I don't think I can do anything about it, but I'll look.

> maybe the tiles should open after some configurable timeout, in case there are other targets for dragging. It didn't happen, yet, but I am waiting for such a situation...

Working on some ideas. In the latest code, you can shake the mouse left and right a few times to cancel.

> I think the tiles should not be rounded, it's a bit irritating, if something lurks through the holes, especially when animated

Hah, yeah that could be unnerving. Just override the border-radius in user styles
`.pageTile { border-radius:none; }` should do the trick (untested )

> I would generally prefer the look of the context menu (but big) and it would be more consistent to use the same design. I guess, something (e.g. colors) that works with the context menu should also work with the tiles.

That was my original idea, but it just didn't scale well. It needed a separate interface. I could add a button to copy the qm layout over.

> I have several engines with longer titles, I would suggest attaching the icon to the bottom and a smaller font size (though I already changed it in CSS).

Accommodating all string lengths is nearly impossible, and getting something that looks nice for every DPI is a challenge, but I'll see if some scaling can be done.

**Comment by ssborbis** [comment]
> drag events seem to capture keypress events, and the first ESC will cancel the drag ( in FF at least ). It doesn't register with keypress listeners so I can't see it. It doesn't even throw a dragend event. You need to press ESC twice. I don't think I can do anything about it, but I'll look.

> Did you mean elsewhere on the desktop? I'm trying some event listeners and nothing seems to register a click outside the browser or elsewhere in the browser UI as an event ( no window blur, etc )

Got it. Events were on the parent window.

**Comment by hg42** [comment]
> > when clicking on something outside of the tiles, they should close
> Did you mean elsewhere on the desktop?

would be even nicer, but I meant inside the page, which may be surprising, but I have a bigger tile number than engines, so about 1/3 of the page is still free. I would eventually also reduce the size of the tiles area via CSS to be able to click outside.

Motivation: For some reason clicking is usually easier than pressing escape, because I am using the mouse in this situation. I could also imagine pressing another mouse button combination (e.g. adding the right button while dragging) as end of the operation.

> I'm trying some event listeners and nothing seems to register a click outside the browser or elsewhere in the browser UI
yes, I am aware of this...
May be the strategy could be much simpler:
just close the tiles, when the dragging button is released (or generally dragging is finished), then the other cases are no more necessary

> drag events seem to capture keypress events, ...
well just close the tiles at the end of the drag
Either you have a target at that point (dropped on a tile) or not (escape, dropped somewhere else)

> > maybe the tiles should open after some configurable timeout, in case there are other targets for dragging. It didn't happen, yet, but I am waiting for such a situation...

nor sure about that...this was just a feeling...I am still searching for a situation where it would matter or help...
it mainly depends on other extensions doing similar things...most of the time I do not drag text, but often links (e.g. to bookmark folders on the bookmarks bar).
I probably felt it would happen there...but links are not selected and thus don't trigger this kind of drag...seems to be safe.

Ok, just by saying it, I found a situation. I sometimes drag text to an editor or text input fields in another window.

> Working on some ideas. In the latest code, you can shake the mouse left and right a few times to cancel.

yeah, that would eventually help, while it may also cancel if you are unsure where to drop (shaking the mouse)

> > I think the tiles should not be rounded, it's a bit irritating, if something lurks through the holes, especially when animated
> 
> Hah, yeah that could be unnerving. Just override the border-radius in user styles
> `.pageTile { border-radius:none; }` should do the trick (untested )

I tried, actually `border-radius: 0`, but it didn't work ad hoc, may be I made a syntax error or something...
e.g. my first try used .PageTile instead of .pageTile, wait I used .CS_pageTile I think...will try again if I am at my PC
> > I would generally prefer the look of the context menu (but big) and it would be more consistent to use the same design. I guess, something (e.g. colors) that works with the context menu should also work with the tiles.
> 
> That was my original idea, but it just didn't scale well. It needed a separate interface. I could add a button to copy the qm layout over.
> 
> > I have several engines with longer titles, I would suggest attaching the icon to the bottom and a smaller font size (though I already changed it in CSS).
> 
> Accommodating all string lengths is nearly impossible, and getting something that looks nice for every DPI is a challenge, but I'll see if some scaling can be done.

**Comment by hg42** [comment]
well, for some reasons, I usually don't use the quick menu. It seems to be too complicated with the configurations I tried (mainly in conjunction with other extensions etc.).

But looking at the tile solution I get the feeling, this could work exactly the same with the quick menu.
In fact we already have a "hold" mouse button feature. If I set it to the left mouse button, it behaves quite similar, but not exactly. It waits some time (while not moving the mouse) to distinguish from a drag, before opening the quick menu.
Dragging is more convenient and faster, you already move to the target button, before it is even displayed.

So [sorry, a feature request] it would be nice to add a "drag" setting to it (not sure if it would work directly, but at least dropping is already implemented).

I guess, I would use this instead of tiles, because it works with shorter distances for the mouse (quicker and identical usage, same places for engines etc.).
I could even make the quick menu bigger.
Should I open another "issue" for that?

**Comment by Amin884** [comment]
> 
> 
> @Amin884
> 
> > there is a new problem.sometimes when you select a text and drag it, nothing is selected in the pop-up screen.you have to select the text again.
> 
> I think I have this figured out. I'm guessing you're using a HOLD method for opening the quick menu?
no just by dragging text.it rarely happens recently.
btw, new update is great

**Comment by ssborbis** [comment]
@hg42 
>I have a bigger tile number than engines, so about 1/3 of the page is still free

If the tiles are actually there, just empty, ( no search engine there ) they should close when you drop / click.

> 
 `.pageTile { border-radius:0; }` worked for me, but I am on slightly newer code locally. 

>  I guess, I would use this instead of tiles, because it works with shorter distances for the mouse (quicker and identical usage, same places for engines etc.).

So you'd like a "drag" opening method added to the quick menu?

**Comment by hg42** [comment]
> > I have a bigger tile number than engines, so about 1/3 of the page is still free
> If the tiles are actually there, just empty, ( no search engine there ) they should close when you drop / click.

no, the empty tiles are not drawn, I'm just clicking elsewhere on the page. If I would shrink the tiles, I would even have more chance to click beneath.
But anyways, that's only relevant, if end of dragging doesn't close the tiles, which they should in my opinion.

> `.pageTile { border-radius:0; }` worked for me, but I am on slightly newer code locally.

I first need to revive my github repo installation. Currently, I am runnning normal releases.

> So you'd like a "drag" opening method added to the quick menu?

yes

**Comment by ssborbis** [comment]
@hg42 
> Currently, I am runnning normal releases.

That's probably the reason we're seeing different results. The repo and the last release are very different in a number of ways. There are a ton of changes / upgrades.

**Comment by ssborbis** [comment]
@hg42 

Option added. Right now, only really viable in FF due to Chromium-based drag behaving badly over iframes.

**Comment by ssborbis** [comment]
@Amin884 
> no just by dragging text.it rarely happens recently.

I was seeing this issue with this behavior
1. Open qm using a HOLD method
2. close qm
3. drag text to open pagetiles

It was opening the qm on the page before using pagetiles that was causing it for me. Your bug may be slightly different.

**Comment by hg42** [comment]
I am now using the repo version (at 9ae7ba59 but no drag option?)

**Comment by hg42** [comment]
> That's probably the reason we're seeing different results

yes, formatting works now

**Comment by hg42** [comment]
I have a hidden folder (using Hide in the context menu).
It should not be shown in tiles, either.
The root folder "/" is also shown (or can it be used for something? well, it will probably open in *all* sub-engines)

**Comment by ssborbis** [comment]
@hg42 

No drag in the repo yet. I have some changes that need completed first, but it's coded and does work. I added the same "shake to close" as page tiles, although it gets buggy when used over the qm ( drag events get weird over iframes )

> I have a hidden folder (using Hide in the context menu).
It should not be shown in tiles.

I'm not sure how I want to handle that. Since it's easy to add / remove a folder from the tiles, I may leave it to the user to decide what nodes to use, hidden or not. Maybe I'll leave them in the tree, but represent them as hidden with a low opacity, and display them as empty when the menu opens. Minor details...

**Comment by ssborbis** [comment]
big push going up

@hg42 

I disabled the shake-to-close on the qm for now, but the drag option is there. You will get both the qm and pagetiles if both are enabled

**Comment by hg42** [comment]
that was funny... :-)

First, I forgot that the extension is only loaded temporary from the sources... I once had a firefox startup modification... but Murphy demands that it's not working.
Unfortunately I changed my CSS until it was like it was before using the repo...well that made me think again :-)

Second, I looked for "Drag" in the "Click and Hold" menu, and there's none... haha...how blind can I be? the new option is only some mm below...

Also, I wasn't aware, that I can use that preview to configure the tiles. That's nice, and I can use `display: none` on empty tiles (well it worked with the release version, but now the selector seems to be different and see below why I can't find the current selectors).

After "solving" all that, I tested pagetiles. Works well so far, canceling drag also removes the tiles, nice.
While this is very convenient for normal usage...it makes inspecting difficult (impossible?).
Do you have a trick? any tricky way to stop dragging without closing the tiles? maybe a Modifier-Escape or similar?
It's the same problem for screenshots.
Well, I know this is a more general problem, that I get with other menus or dragging situations, too.
One solution for screenshots is using a timeout (some tools can do this). Maybe the debugger has a similar solution...

Quickmenu+Dragging is awesome...
I get all the nice features, like
* exactly positioning the box
* scaling
* predictable positions, so that the drop position can be learned
* folders that open on mouseover etc.

With choosing a much bigger menu (and comparing features to the tiles), there could be some more for quick menus:
* "unfolded" folders (didn't we have this at some time in the past?)
* engine titles

btw. for the tiles I am currently using
`background-position: center bottom 10%;`
to position the icons attached to the bottom with a configurable distance (here 10%). For a smaller tile the distance shrinks automatically.

**Comment by hg42** [comment]
ok, I see the iframe changed class names to a more compact naming scheme (like .empty instead of .pageTilesEmptyTile)

so my tiles formatting mostly works now

**Comment by hg42** [comment]
is it ok to discuss small quickmenu "issues" here, that are related to dragging (but also global)? or should I better open a new issue?

as an example:
hovering over a folder usually results in the back button placed below the mouse (at least in my configuration) and when waiting (depending on the timeout) it switches back again. The same if you hover over the back button, it sometimes switches back to the folder. It happens more often with a short timeout. It would be more convenient, if the you have to leave the area before you can hover again (not sure if that's possible, may be a matter on which occasions the handler is set).

another one:
the configurable action buttons seem not to be drop targets.
I tried "find in page", "copy to clipboard", "<last used engine>" and "instant search"...

third:
tooltips are not shown while dragging (if possible), which would be useful

**Comment by ssborbis** [comment]
> Do you have a trick? any tricky way to stop dragging without closing the tiles? maybe a Modifier-Escape or similar?
It's the same problem for screenshots.

If you're on very recent repo code, check under the Hotkeys tab. I've started putting some commands accessible by keyboard shortcuts. If you enable pageTilesOpen, you can select text, press a keyboard combo and get the menu open - no drag required.

> With choosing a much bigger menu (and comparing features to the tiles), there could be some more for quick menus:
>    "unfolded" folders (didn't we have this at some time in the past?)

Is that what I'm calling group folders?
   
>  engine titles
???

> ok, I see the iframe changed class names to a more compact naming scheme (like .empty instead of .pageTilesEmptyTile)

I moved page tiles to an iframe for security. It causes all kinds of complications, however. Especially in chrome

> but right click is for context menu and I seem to be unable to learn the "hold" button method...no clue why

Can you check the advanced menu as see if you have a value for `quickMenuHoldTimeout` . Another user had that field blank, and I don't know why. But if it's a trend...

> I noticed, that dragging an image(url?) sometimes isn't the same as using the context menu, which is not really unexpected, but you don't always think like that.

There's a built-in API for distinguishing between element types in the context menu. I made my own for the quick menu. They don't always match. I did some accounting for background images which may result it some different behavior.

> hovering over a folder usually results in the back button placed below the mouse (at least in my configuration) and when waiting (depending on the timeout) it switches back again. The same if you hover over the back button, it sometimes switches back to the folder. It happens more often with a short timeout. It would be more convenient, if the you have to leave the area before you can hover again (not sure if that's possible, may be a matter on which occasions the handler is set).

When dragging or just normal hover?

> the configurable action buttons seem not to be drop targets. I tried "find in page", "copy to clipboard", "" and "instant search"...

Most tools don't. I'd say most shouldn't because they don't deal with search terms (which presumably are being dragged), but I'll look into the ones that do.

> tooltips are not shown while dragging (if possible), which would be useful

dragenter, dragexit to the rescue.

**Comment by hg42** [comment]
> you can select text, press a keyboard combo and get the menu open - no drag required

and then DON'T click a folder with many items :-)))

nice, I was quite sure, you already had a solution like that :-)

> Is that what I'm calling group folders

there's an option called "Group Layout" in search engines. This is nice...especially with coloring (I once had such a configuration).
Sorry, I forgot about that option...(and didn't get the naming, though it's reasonable, maybe add a hint, keywords: flat, unfolded).

It's interesting psychologically, because each kind of invoking CS is a little bit different. I removed the group layout when my 3 column sidebar on a 23" screen became to long, the was more space before on the same screen in vertical orientation.
In the context menus I always want subfolders...while on lots of tiles I would use group layout.
Since then I switched from a 3 screen configuration to a single 43" (cheap 200EUR TV). So everything is now kind of small :-) But I didn't reconfigure CS, yet...

I found, that I tend to use the same method of invocation most of the time. Once I loved the sidebar, but nowadays I mostly use the toolbar button (mainly because I now search from there and it is more prominent on the toolbar, a single button with lots of space on both sides.
I sometimes use context menu, when I want to see the titles (rarely used engines), but the grid is more convenient in daily searching (less distance so faster for well known engines).

I think, with my big screen I could probably use group layout for everything.

I currently use a mix of both. Each group has a folder with rarely used engines on the left and important engines follow outside of the folder. So the folder gives the title of the group. This way I am missing the colors but I have the folders for a group title (short...e.g. srch instead of search etc.).

> engine titles ???

in tiles there are titles for each engine (there is enough space), if I use quickmenu I don't have titles, even if I scale the menu. This is why I need tooltips and sometimes use the context menu.

> quickMenuHoldTimeout

it's 250

> built-in API [...] my own for the quick menu

ah, I understand

> When dragging or just normal hover?

interesting, when normal hovering, it switches faster and when dragging I need to move the mouse a little bit.
This only happens in the top left corner, where the back button lives and because I have a folder at the same place.
Theoretically a similar problem could also happen, when hovering over a folder and the submenu has another folder at the same place (I remember I had this at least once and didn't understand, because it can only happen at that single position in my menu structure).

> Most tools don't

yepp :-) and some probably should

> [tooltips] dragenter, dragexit to the rescue

do you mean as a workaround? I tried that, but it doesn't work

**Comment by ssborbis** [comment]
@hg42 

It's nice to hear how others are using this addon. I don't get much feedback in that regard, and there are no analytics of any kind to tell me what's being used and what isn't. 

>  [tooltips] dragenter, dragexit to the rescue
do you mean as a workaround? I tried that, but it doesn't work

I didn't actually do anything about that. `title=` tooltips are handled by the browser and don't show on drag, and rolling my own will be a bit messy because they will overflow the menu iframe container at times, so they need to be shown on the parent window inside their own iframe to keep engines hidden from malicious websites, Doable,but a pain.

>  quickMenuHoldTimeout
it's 250

k, different problem then

>  Most tools don't
yepp :-) and some probably should

They do now. All tools respond to drop as if it were a click

> interesting, when normal hovering, it switches faster and when dragging I need to move the mouse a little bit.
This only happens in the top left corner, where the back button lives and because I have a folder at the same place.
Theoretically a similar problem could also happen, when hovering over a folder and the submenu has another folder at the same place (I remember I had this at least once and didn't understand, because it can only happen at that single position in my menu structure).

Can you post a gif?

**Comment by hg42** [comment]
@ssborbis

As a developer, I know of that lack of detailed user scenarios.
Sometimes I think I'm talking too much :-) so it's nice to get feedback like this

tooltip: I already thought it's a browser thingy...

hover:
![back-and-forth](https://user-images.githubusercontent.com/4707597/108413789-ba519100-722b-11eb-82c2-82008d9823ec.gif)
note, I am not clicking buttons, in the first case (opened by a hotkey), I can leave the mouse alone and it switches forever.
In the dragging case, I have to move the mouse but not leave the button area...

**Comment by hg42** [comment]
If hover is disabled, hovering still works while dragging (nice!).
In fact, for me, it's more natural to click the buttons when not hovering.
I guess, this may be a matter of taste.

**Comment by ssborbis** [comment]
Oh ok, you must have a value set for `openFoldersOnHoverTimeout`. The problem is the back button activating on hover as well, gotcha. 

> If hover is disabled, hovering still works while dragging (nice!).

Yep, drag and mouse have separate event handlers ( a pain sometimes )

**Comment by hg42** [comment]
btw, I use it like this currently:

![image](https://user-images.githubusercontent.com/4707597/109316820-49723080-784c-11eb-8384-ca4d8fe63579.png)

and I'm quite happy.
Though, for an unfolded folder it's questionable, if it should open on hover, why should one want this?
And I cannot disable this while dragging, nor can I set the timeout, so I often land inside it accidentally.

(note: I hadn't a chance to try your latest changes, in case you already have a solution)

**Comment by ssborbis** [comment]
> Though, for an unfolded folder it's questionable, if it should open on hover, why should one want this?

You probably wouldn't. It's just the default behavior. The group folders and flat layout were tacked on without much design consideration. They need work
