### ISSUE TITLE
Normal shortcut like C-c/C-tab won't work as expected with Quick Menu

### ISSUE THREAD

**Issue by c02y** [ssborbis/ContextSearch-web-ext#371]
When I select text on a web page, after the Quick Menu popups, the shortcut like C-c to copy the text or C-tab to switch tabs won't work at all
I have to use the following solution:
1. Quickly C-c to copy the text before the Quick Menu popups(C-tab won't work at all once I select the text), but I can not find any configuration for the delay of the Quick Menu
2. Use the Copy button in the Quick Menu
3. Use AutoCopy, BTW, it doesn't work all.

-----
UPDATE:
FYI: C-tab to switch tabs doesn't work only in Vivaldi, in Firefox/Chrome it works normally, in Vivaldi, it switches focus to the Search Engines in Quick Menu. They all use the same extension version and same extension configuration.

I already tested in Vivaldi Private Window with only ContextSearch extension enabled.

**Comment by ssborbis** [comment]
I'm not seeing that, but I'm on the most recent dev code. If you're willing, backup your config and try the latest code from the development branch. It could use some debuggers anyway.

**Comment by c02y** [comment]
I tried the development branch of this extension in Firefox, found that 
1. If I load my old configuration, I still got the issue
2. If I use default configuration + enable the QuickMenu, the issue is gone
3. I reinstall the stable version in the extension store of Firefox, using the simple configuration I just mentioned, the problem is gone
4. I uninstall the stable extension in Vivaldi, use the simple configuration, use the only extension in Vivaldi Private window, the "unselect" issue in input textarea is gone, C-c or Backspace works normally, but C-tab to switch tabs doesn't work, C-tab now unselect the selected text and do nothing more. (old issue is it will switch focus in search engines in Quick Menu)

So the conclusion is:
1. Something is wrong in my configuration of this extension
2. Vivaldi got its own issue with the C-tab issue.

I'll update this thread once I got something new.

**Comment by ssborbis** [comment]
send me your config and I'll try on my setup

**Comment by c02y** [comment]
[ContextSearchOptions.json.zip](https://github.com/ssborbis/ContextSearch-web-ext/files/7188145/ContextSearchOptions.json.zip)
Here it is.

**Comment by ssborbis** [comment]
It does look like some config settings are conflicting. I noticed while using your config, ESC no longer closes the quick menu. I'll let you know when I find anything.

**Comment by ssborbis** [comment]
Unrelated bugs, but I fixed ESC not working when the option quickMenuCloseOnSearch is disabled ( as you have in your config ).
I also cancelled some qm key events ( namely Tab ) when also using mod keys other than Shift. That seems to have fixed the Vivaldi issue. Check the latest code in the dev branch and let me know.

**Comment by c02y** [comment]
With my config, in input textarea, Firefox, once the Quick Menu popups, selected text still gets unselected.
Vivaldi still has the same issue.

And yes, the C-tab in Vivaldi is fixed.

**Comment by ssborbis** [comment]
Ok, good the vivaldi issue is fixed.

The deselecting issue is due to the popup menu getting focus after it's open I'll see about adding an option to not steal focus, but that may take some time. It should, however, return focus to the selected text in an input box if you close the menu using ESC

**Comment by c02y** [comment]
BTW: C-c to copy the selected text once the Quick Menu popups is there ( in none input textarea) both in Firefox and Vivaldi.

And it would be better to add a delay config for the Quick Menu to popup

**Comment by ssborbis** [comment]
Are you not actually using the menu in these instances? The dev code added modifier keys to the auto open function of the quick menu. You can set it to only open the menu when you select text while holding, for instance, the Ctrl key. This also works to cancel the auto menu when you don't want it to open. If you don't set a modifier key with auto open, holding down a modifier key when you release the mouse after selecting text cancels the popup.

**Comment by c02y** [comment]
I managed to get C-c work, but it needs a modifier key like Ctrl or the mouse to do that.

A simple solution is to add a delay for the Quick Menu popup so most of the time I am able to C-c the text before Quick Menu popups, for the other situations I can just use the Copy button in Quick Menu

**Comment by ssborbis** [comment]
Does Advanced -> Auto Copy work now?

**Comment by c02y** [comment]
Works for Firefox but not Vivaldi.

I tried AutoCopy function from another plugin a long time ago, disabled it at the end since it is not friendly to my clip manager.
so, even if it works I wouldn't enable it. But I can test it for you.

**Comment by ssborbis** [comment]
No worries. I'll look into other options.

**Comment by ssborbis** [comment]
added advanced option quickMenuFocusOnOpen

disabling should keep the focus on the page vs the quick menu on open

**Comment by c02y** [comment]
I'm sorry, what `quickMenuFocusOnOpen` does exactly?

I tried the latest code in Firefox
1. C-c won't work
2. selected text in input textarea gets unselected once the Quick Menu popups 

And exactly the same in Vivaldi:

**Comment by ssborbis** [comment]
Did you disable advanced -> quickMenuFocusOnOpen ?

On:
![on](https://user-images.githubusercontent.com/24310997/133892467-c6e977b2-cebc-45dd-b913-ad4569c55732.gif)

Off:
![off](https://user-images.githubusercontent.com/24310997/133892472-539df3f5-165f-470d-8fdf-7eefd015f784.gif)

**Comment by c02y** [comment]
It is enabled by default, I thought the default value is used to fix the problem, sorry I didn't test the other value.

After I disabled it, C-c does work as expected.

But C-tab won't work in Vivaldi

**Comment by ssborbis** [comment]
Ok, I just tested with the latest code and I think the Vivaldi issue is fixed.

**Comment by c02y** [comment]
OK, thank you very much.

It seems the input-textarea/C-c/C-tab issues are all fixed in both Firefox and Vivaldi.

Any plans to release the version to the extension store of Firefox and Chrome?

**Comment by ssborbis** [comment]
No release until the dev code has a thorough shakedown. Maybe November.
