### ISSUE TITLE
feature request: enable filtering based on element for recent search engines.

### ISSUE THREAD

**Issue by rezad1393** [ssborbis/ContextSearch-web-ext#712]
when I use great feature "Show recently used engines at the top of the menu" it shows all the search engines I have used recently.
which is cool.

but even better would be if it was filtered based on elements.

for example I have search engines that are for image elements  and only show on images but when I right click an image the recent searches are still shown that are not image only.

this a feature request and not a bug. so maybe low priority but still useful.

**Comment by ssborbis** [comment]
I think I have this fixed now locally. It should be in the next release.

**Comment by rezad1393** [comment]
> [@rezad1393](https://github.com/rezad1393): Does this affect version 1.47.15 or ulterior? And if so, is this report specifically about the Quick Menu?

it still the same for me and I don't see the issue fixed.
I have the 1.47.15 version installed.

what is the "ulterior"?

**Comment by Chealer** [comment]
Thank you @rezad1393. There is no released version ulterior to 1.47.15. I just wanted to check that your issue was still current.

Is this report specifically about the Quick Menu?

**Comment by Chealer** [comment]
Ah, sorry, I see you are indeed referring to the context sub-menu.

Regardless, I understand the problem now. The filtering added for issue #403 does not apply to recently used tools.

Since this is an ITS, please retitle this as an issue report. I would suggest:

> Contextual menus: Recently used tools cannot be filtered based on target type

**Comment by rezad1393** [comment]
> [@rezad1393](https://github.com/rezad1393): an ITS is an Issue Tracking System, like this one. Tickets in ITSs are issue reports. **Technically**, they are not requests, so determining the solution(s) is secondary.
> 
> This ticket’s title is incorrect because it is phrased as a request rather than as an issue report. But more importantly, it is unclear, since:
> 
>     1. it fails to mention it is about contextual menus
> 
>     2. uses the very vague (and arguably incorrect) term "element" (rather than "target")
> 
>     3. and only refers to search engines.
> 
> 
> I am unsure which term best generalizes "search engines", but unless you see something better, the following title would solve all of of that:
> 
> > Contextual menus: Recently used menu elements (sites) cannot be filtered based on target type

I have no idea if you are a bot or just padding your resumes with "participation" is github.

the github system -as far as I know- doesn't have a separate feature request.
any project use sub-type for request and issues but they are all tracked "here" in issues.


if you have something about adding this feature, please carry on, if not then I am really here for github version grammar nazi.

**Comment by Chealer** [comment]
@rezad1393: I don't know if you're here to genuinely contribute or chase Godwin points, and I wonder what you mean by "for github version grammar nazi". But you are right that GitHub does not track feature requests apart from bug reports (like most others development platforms).

I am **not** saying this ticket does not belong here. I merely explained it is not **presented** correctly. As always, [reports should first focus on the problem](https://make.wordpress.org/core/handbook/contribute/trac/#:~:text=Concentrating%20on%20the%20problem). For example:
- 🚫Make the font red
- ☑Text lacks contrast

It is acceptable (and even best) to offer solutions, in the ticket's description.

In this case:
- 🚫feature request: enable filtering based on element for recent search engines.
- ☑Contextual menus include irrelevant recently used elements (sites) for certain target types
